// Children
export const VIEW_CHILD = 'VIEW_CHILD';
export const VIEW_CHILD_SUCCESS = 'VIEW_CHILD_SUCCESS';
export const VIEW_CHILD_ERROR = 'VIEW_CHILD_ERROR';
export const ADD_CHILD = 'ADD_CHILD';
export const ADD_CHILD_SUCCESS = 'ADD_CHILD_SUCCESS';
export const ADD_CHILD_ERROR = 'ADD_CHILD_ERROR';
export const UPDATE_CHILD_PENDING = 'UPDATE_CHILD_PENDING';
export const UPDATE_CHILD_SUCCESS = 'UPDATE_CHILD_SUCCESS';
export const UPDATE_CHILD_ERROR = 'UPDATE_CHILD_ERROR';

// Chores
export const REQ_CHORES_PENDING = 'REQ_CHORES_PENDING';
export const REQ_CHORES_SUCCESS = 'REQ_CHORES_SUCCESS';
export const REQ_CHORES_ERROR = 'REQ_CHORES_ERROR';

export const REQ_CHORE_PENDING = 'REQ_CHORE_PENDING';
export const REQ_CHORE_SUCCESS = 'REQ_CHORE_SUCCESS';
export const REQ_CHORE_ERROR = 'REQ_CHORE_ERROR';

export const ADD_CHORE_PENDING = 'ADD_CHORE_PENDING';
export const ADD_CHORE_SUCCESS = 'ADD_CHORE_SUCCESS';
export const ADD_CHORE_ERROR = 'ADD_CHORE_ERROR';

export const UPDATE_CHORE_PENDING = 'UPDATE_CHORE_PENDING';
export const UPDATE_CHORE_SUCCESS = 'UPDATE_CHORE_SUCCESS';
export const UPDATE_CHORE_ERROR = 'UPDATE_CHORE_ERROR';

export const DELETE_CHORE_PENDING = 'DELETE_CHORE_PENDING';
export const DELETE_CHORE_SUCCESS = 'DELETE_CHORE_SUCCESS';
export const DELETE_CHORE_ERROR = 'DELETE_CHORE_ERROR';

// REWARDS
export const REQ_REWARDS_PENDING = 'REQ_REWARDS_PENDING';
export const REQ_REWARDS_SUCCESS = 'REQ_REWARDS_SUCCESS';
export const REQ_REWARDS_ERROR = 'REQ_REWARDS_ERROR';

export const REQ_REWARD_PENDING = 'REQ_REWARD_PENDING';
export const REQ_REWARD_SUCCESS = 'REQ_REWARD_SUCCESS';
export const REQ_REWARD_ERROR = 'REQ_REWARD_ERROR';

export const ADD_REWARD_PENDING = 'ADD_REWARD_PENDING';
export const ADD_REWARD_SUCCESS = 'ADD_REWARD_SUCCESS';
export const ADD_REWARD_ERROR = 'ADD_REWARD_ERROR';

export const UPDATE_REWARD_PENDING = 'UPDATE_REWARD_PENDING';
export const UPDATE_REWARD_SUCCESS = 'UPDATE_REWARD_SUCCESS';
export const UPDATE_REWARD_ERROR = 'UPDATE_REWARD_ERROR';

export const DELETE_REWARD_PENDING = 'DELETE_REWARD_PENDING';
export const DELETE_REWARD_SUCCESS = 'DELETE_REWARD_SUCCESS';
export const DELETE_REWARD_ERROR = 'DELETE_REWARD_ERROR';

// USERS
export const SIGNUP_USER_PENDING = 'SIGNUP_USER_PENDING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const SET_LOGGEDIN_PENDING = 'SET_LOGGEDIN_PENDING';
export const SET_LOGGEDIN_SUCCESS = 'SET_LOGGEDIN_SUCCESS';
export const SET_LOGGEDIN_ERROR = 'SET_LOGGEDIN_ERROR';

// LOGIN
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// USER INFORMATION
export const USER_INFO_PENDING = 'USER_INFO_PENDING';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';
