// Children
export const VIEW_CHILD = 'VIEW_CHILD';
export const VIEW_CHILD_SUCCESS = 'VIEW_CHILD_SUCCESS';
export const VIEW_CHILD_ERROR = 'VIEW_CHILD_ERROR';
export const ADD_CHILD = 'ADD_CHILD';
export const ADD_CHILD_SUCCESS = 'ADD_CHILD_SUCCESS';
export const ADD_CHILD_ERROR = 'ADD_CHILD_ERROR';

// Chores
export const VIEW_CHORES = 'VIEW_CHORES';
export const VIEW_CHORES_SUCCESS = 'VIEW_CHORES_SUCCESS';
export const VIEW_CHORES_ERROR = 'VIEW_CHORES_ERROR';
export const ADD_CHORE = 'ADD_CHORE';
export const ADD_CHORE_SUCCESS = 'ADD_CHORE_SUCCESS';
export const ADD_CHORE_ERROR = 'ADD_CHORE_ERROR';
export const SET_CURRENT_CHORE = 'SET_CURRENT_CHORE';
export const SET_CURRENT_CHORE_SUCCESS = 'SET_CURRENT_CHORE_SUCCESS';
export const SET_CURRENT_CHORE_ERROR = 'SET_CURRENT_CHORE_ERROR';
export const UPDATE_CHORE = 'UPDATE_CHORE';
export const UPDATE_CHORE_SUCCESS = 'UPDATE_CHORE_SUCCESS';
export const UPDATE_CHORE_ERROR = 'UPDATE_CHORE_ERROR';
export const DELETE_CHORE = 'DELETE_CHORE';
export const DELETE_CHORE_SUCCESS = 'DELETE_CHORE_SUCCESS';
export const DELETE_CHORE_ERROR = 'DELETE_CHORE_ERROR';

// Rewards
export const VIEW_REWARD = 'VIEW_REWARD';
export const VIEW_REWARD_SUCCESS = 'VIEW_REWARD_SUCCESS';
export const VIEW_REWARD_ERROR = 'VIEW_REWARD_ERROR';
export const ADD_REWARD = 'ADD_REWARD';
export const ADD_REWARD_SUCCESS = 'ADD_REWARD_SUCCESS';
export const ADD_REWARD_ERROR = 'ADD_REWARD_ERROR';
export const SET_CURRENT_REWARDS = 'SET_CURRENT_REWARDS';
export const SET_CURRENT_REWARDS_SUCCESS = 'SET_CURRENT_REWARDS_SUCCESS';
export const SET_CURRENT_REWARDS_ERROR = 'SET_CURRENT_REWARDS_ERROR';
export const UPDATE_REWARD = 'UPDATE_REWARD';
export const UPDATE_REWARD_SUCCESS = 'UPDATE_REWARD_SUCCESS';
export const UPDATE_REWARD_ERROR = 'UPDATE_REWARD_ERROR';
export const DELETE_REWARD = 'DELETE_REWARD';
export const DELETE_REWARD_SUCCESS = 'DELETE_REWARD_SUCCESS';
export const DELETE_REWARD_ERROR = 'DELETE_REWARD_ERROR';
